### ISSUE TITLE
NullPointerException with /warpinfo

### ISSUE THREAD

**Issue by oskar3123** [Jona123/Warpalicious#3]
`/warpinfo <warpname>` generates a NullPointerException when the warps owner is unknown (null)
```
org.bukkit.command.CommandException: Unhandled exception executing command 'warpinfo' in plugin Warpalicious v1.5.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) ~[spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
        at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1345) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1180) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
        at java.lang.String.replace(Unknown Source) ~[?:1.8.0_111]
        at nl.datdenkikniet.warpalicious.commands.WarpinfoCommand.onCommand(WarpinfoCommand.java:68) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
        ... 15 more
```

**Comment by Jona123** [comment]
Thanks for the report in a proper format. Fixed it, but the commit/update might take a while as I'm also working on particles and delays.

Will mark as "resolved" when I've updated it

**Comment by Jona123** [comment]
Fixed!
