### ISSUE TITLE
LoadConfiguration breaks on 1.12-pre5

### ISSUE THREAD

**Issue by klugemonkey** [Jona123/Warpalicious#8]
[23:55:31 ERROR]: Error occurred while enabling Warpalicious v1.7.1 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
        at nl.datdenkikniet.warpalicious.config.CustomConfig.reloadCustomConfig(CustomConfig.java:46) ~[?:?]
        at nl.datdenkikniet.warpalicious.config.CustomConfig.getCustomConfig(CustomConfig.java:29) ~[?:?]
        at nl.datdenkikniet.warpalicious.WarpaliciousPlugin.checkTeleportModes(WarpaliciousPlugin.java:80) ~[?:?]
        at nl.datdenkikniet.warpalicious.WarpaliciousPlugin.onEnable(WarpaliciousPlugin.java:37) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12-pre5.jar:git-Spigot-6629162-cda27c9]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12-pre5.jar:git-Spigot-6629162-cda27c9]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12-pre5.jar:git-Spigot-6629162-cda27c9]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot-1.12-pre5.jar:git-Spigot-6629162-cda27c9]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot-1.12-pre5.jar:git-Spigot-6629162-cda27c9]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.12-pre5.jar:git-Spigot-6629162-cda27c9]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.12-pre5.jar:git-Spigot-6629162-cda27c9]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.12-pre5.jar:git-Spigot-6629162-cda27c9]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12-pre5.jar:git-Spigot-6629162-cda27c9]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12-pre5.jar:git-Spigot-6629162-cda27c9]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Comment by oskar3123** [comment]
~~What is your Spigot version?~~
I'm stupid, will check this out

**Comment by oskar3123** [comment]
This has been fixed, you can wait for Jona to upload to spigot or download from [here](https://github.com/Jona123/Warpalicious/releases/tag/v1.7.2).

**Comment by klugemonkey** [comment]
Awesome, thanks, will test it.
